# Generated by Django 4.1.7 on 2023-07-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devgigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
