# Generated by Django 4.1.7 on 2023-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devgigs', '0002_alter_listing_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='website',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
