# Generated by Django 4.1.7 on 2023-07-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devgigs', '0003_listing_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
